routes/web.php
<?php
Route::redirect('/', 'admin/home');

Auth::routes(['register' => false]);

// Change Password Routes...
Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
Route::patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::delete('permissions_mass_destroy', 'Admin\PermissionsController@massDestroy')->name('permissions.mass_destroy');
    Route::resource('roles', 'Admin\RolesController');
    Route::delete('roles_mass_destroy', 'Admin\RolesController@massDestroy')->name('roles.mass_destroy');
    Route::resource('users', 'Admin\UsersController');
    Route::delete('users_mass_destroy', 'Admin\UsersController@massDestroy')->name('users.mass_destroy');
    Route::resource('fpo', 'Admin\fpoController');
    Route::resource('farmer', 'Admin\farmerController');
     
});

app/fpo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class fpo extends Model
{
    //
}

app/Http/Controllers/Admin/fpoController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class fpoController extends Controller
{
    /**
     * Display a listing of User.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
     
       return view('admin.fpo.create');
    }

}

resources/views/admin/fpo/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.fpo.title_singular') }}
    </div>

    <div class="card-body">
        <form action="" method="POST" enctype="multipart/form-data">
            @csrf
        <div class="row">
            <div class="form-group col{{ $errors->has('fpo_name') ? 'has-error' : '' }}">
                <label for="fpo_name">{{ trans('cruds.fpo.fields.fpo_name') }}*</label>
                <input type="text" id="fpo_name" name="fpo_name" class="form-control"
                    value="{{ old('fpo_name', isset($fpo) ? $fpo->fpo_name : '') }}" required>
                @if($errors->has('fpo_name'))
                <em class="invalid-feedback">
                    {{ $errors->first('fpo_name') }}
                </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.fpo.fields.fpo_name_helper') }}
                </p>
            </div>
            <div class="form-group col{{ $errors->has('address') ? 'has-error' : '' }}">
                <label for="address">{{ trans('cruds.fpo.fields.address') }}*</label>
                <input type="address" id="address" name="address" class="form-control"
                    value="{{ old('address', isset($fpo) ? $fpo->address : '') }}" required>
                @if($errors->has('address'))
                <em class="invalid-feedback">
                    {{ $errors->first('address') }}
                </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.fpo.fields.address_helper') }}
                </p>
            </div>
        </div>
        <div class="row">
            <div class="form-group col {{ $errors->has('taluka') ? 'has-error' : '' }}">
                <label for="taluka">{{ trans('cruds.fpo.fields.taluka') }}*</label>
                <input type="taluka" id="taluka" name="taluka" class="form-control" required>
                @if($errors->has('taluka'))
                <em class="invalid-feedback">
                    {{ $errors->first('taluka') }}
                </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.fpo.fields.taluka_helper') }}
                </p>
            </div>
            <div class="form-group col {{ $errors->has('district') ? 'has-error' : '' }}">
                <label for="district">{{ trans('cruds.fpo.fields.district') }}*</label>
                <input type="district" id="district" name="district" class="form-control" required>
                @if($errors->has('district'))
                <em class="invalid-feedback">
                    {{ $errors->first('district') }}
                </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.fpo.fields.district_helper') }}
                </p>
            </div>
        </div>
        <div class="row">
            <div class="form-group col {{ $errors->has('state') ? 'has-error' : '' }}">
                <label for="state">{{ trans('cruds.fpo.fields.state') }}*</label>
                <input type="state" id="state" name="state" class="form-control" required>
                @if($errors->has('state'))
                <em class="invalid-feedback">
                    {{ $errors->first('state') }}
                </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.fpo.fields.state_helper') }}
                </p>
            </div>
            <div class="form-group col {{ $errors->has('email') ? 'has-error' : '' }}">
                <label for="email">{{ trans('cruds.fpo.fields.email') }}*</label>
                <input type="email" id="email" name="email" class="form-control" required>
                @if($errors->has('email'))
                <em class="invalid-feedback">
                    {{ $errors->first('email') }}
                </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.fpo.fields.email_helper') }}
                </p>
            </div>
        </div>
        <div class="row">
            <div class="form-group col {{ $errors->has('contact_person') ? 'has-error' : '' }}">
                <label for="contact_person">{{ trans('cruds.fpo.fields.contact_person') }}*</label>
                <input type="contact_person" id="contact_person" name="contact_person" class="form-control" required>
                @if($errors->has('contact_person'))
                <em class="invalid-feedback">
                    {{ $errors->first('contact_person') }}
                </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.fpo.fields.contact_person_helper') }}
                </p>
            </div>
            <div class="form-group col {{ $errors->has('mobile_no') ? 'has-error' : '' }}">
                <label for="mobile_no">{{ trans('cruds.fpo.fields.mobile_no') }}*</label>
                <input type="mobile_no" id="mobile_no" name="mobile_no" class="form-control" required>
                @if($errors->has('mobile_no'))
                <em class="invalid-feedback">
                    {{ $errors->first('mobile_no') }}
                </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.fpo.fields.mobile_no_helper') }}
                </p>
            </div>
        </div>
            <div class="form-group row align-items-end{{ $errors->has('gst_no') ? 'has-error' : '' }}">
                <div class="col">
                <label for="gst_no">{{ trans('cruds.fpo.fields.gst_no') }}*</label>
                <input type="gst_no" id="gst_no" name="gst_no" class="form-control" required>
                @if($errors->has('gst_no'))
                <em class="invalid-feedback">
                    {{ $errors->first('gst_no') }}
                </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.fpo.fields.gst_no_helper') }}
                </p>
            </div>
                <div class="input-group mb-3 col">
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="gstInputFile">
                        <label class="custom-file-label" for="gstInputFile">Choose
                            file</label>
                    </div>
                    <div class="input-group-append">
                        <span class="input-group-text" id="">Upload</span>
                    </div>
                </div>
            </div>
            <div class="form-group  row align-items-end {{ $errors->has('tan_no') ? 'has-error' : '' }}">
                <div class="col">
                <label for="tan_no">{{ trans('cruds.fpo.fields.tan_no') }}*</label>
                <input type="tan_no" id="tan_no" name="tan_no" class="form-control" required>
                @if($errors->has('tan_no'))
                <em class="invalid-feedback">
                    {{ $errors->first('tan_no') }}
                </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.fpo.fields.tan_no_helper') }}
                </p>
            </div>
                <div class="input-group mb-3 col ">
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="tanInputFile">
                        <label class="custom-file-label" for="tanInputFile">Choose
                            file</label>
                    </div>
                    <div class="input-group-append">
                        <span class="input-group-text" id="">Upload</span>
                    </div>
                </div>
            </div>
            <div class="form-group  row align-items-end {{ $errors->has('pan_no') ? 'has-error' : '' }}">
               <div class="col">
                <label for="pan_no">{{ trans('cruds.fpo.fields.pan_no') }}*</label>
                <input type="pan_no" id="pan_no" name="pan_no" class="form-control" required>
                @if($errors->has('pan_no'))
                <em class="invalid-feedback">
                    {{ $errors->first('pan_no') }}
                </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.fpo.fields.pan_no_helper') }}
                </p>
            </div>
                <div class="input-group mb-3 col ">
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="panInputFile">
                        <label class="custom-file-label" for="panInputFile">Choose
                            file</label>
                    </div>
                    <div class="input-group-append">
                        <span class="input-group-text" id="">Upload</span>
                    </div>
                </div>
            </div>
            <div class="form-group row align-items-end {{ $errors->has('cin_no') ? 'has-error' : '' }}">
                <div class=" col">
                    <label for="cin_no">{{ trans('cruds.fpo.fields.cin_no') }}*</label>
                    <input type="cin_no" id="cin_no" name="cin_no" class="form-control" required>
                    @if($errors->has('cin_no'))
                    <em class="invalid-feedback">
                        {{ $errors->first('cin_no') }}
                    </em>
                    @endif
                    <p class="helper-block">
                        {{ trans('cruds.fpo.fields.cin_no_helper') }}
                    </p>
                </div>
                <div class="input-group mb-3 col">
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="cinInputFile">
                        <label class="custom-file-label" for="cinInputFile">Choose
                            file</label>
                    </div>
                    <div class="input-group-append">
                        <span class="input-group-text" id="">Upload</span>
                    </div>
                </div>
            </div>







            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>


    </div>
</div>
@endsection

resources/views/admin/fpo/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.user.title_singular') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.users.update", [$user->id]) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                <label for="name">{{ trans('cruds.user.fields.name') }}*</label>
                <input type="text" id="name" name="name" class="form-control" value="{{ old('name', isset($user) ? $user->name : '') }}" required>
                @if($errors->has('name'))
                    <em class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.user.fields.name_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                <label for="email">{{ trans('cruds.user.fields.email') }}*</label>
                <input type="email" id="email" name="email" class="form-control" value="{{ old('email', isset($user) ? $user->email : '') }}" required>
                @if($errors->has('email'))
                    <em class="invalid-feedback">
                        {{ $errors->first('email') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.user.fields.email_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">
                <label for="password">{{ trans('cruds.user.fields.password') }}</label>
                <input type="password" id="password" name="password" class="form-control">
                @if($errors->has('password'))
                    <em class="invalid-feedback">
                        {{ $errors->first('password') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.user.fields.password_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('roles') ? 'has-error' : '' }}">
                <label for="roles">{{ trans('cruds.user.fields.roles') }}*
                    <span class="btn btn-info btn-xs select-all">{{ trans('global.select_all') }}</span>
                    <span class="btn btn-info btn-xs deselect-all">{{ trans('global.deselect_all') }}</span></label>
                <select name="roles[]" id="roles" class="form-control select2" multiple="multiple" required>
                    @foreach($roles as $id => $roles)
                        <option value="{{ $id }}" {{ (in_array($id, old('roles', [])) || isset($user) && $user->roles()->pluck('name', 'id')->contains($id)) ? 'selected' : '' }}>{{ $roles }}</option>
                    @endforeach
                </select>
                @if($errors->has('roles'))
                    <em class="invalid-feedback">
                        {{ $errors->first('roles') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.user.fields.roles_helper') }}
                </p>
            </div>
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>


    </div>
</div>
@endsection

resources/views/admin/fpo/index.blade.php
@extends('layouts.admin')
@section('content')
@can('users_manage')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.users.create") }}">
                {{ trans('global.add') }} {{ trans('cruds.user.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.user.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-User">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.user.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.user.fields.name') }}
                        </th>
                        <th>
                            {{ trans('cruds.user.fields.email') }}
                        </th>
                        <th>
                            {{ trans('cruds.user.fields.roles') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($users as $key => $user)
                        <tr data-entry-id="{{ $user->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $user->id ?? '' }}
                            </td>
                            <td>
                                {{ $user->name ?? '' }}
                            </td>
                            <td>
                                {{ $user->email ?? '' }}
                            </td>
                            <td>
                                @foreach($user->roles()->pluck('name') as $role)
                                    <span class="badge badge-info">{{ $role }}</span>
                                @endforeach
                            </td>
                            <td>
                                <a class="btn btn-xs btn-primary" href="{{ route('admin.users.show', $user->id) }}">
                                    {{ trans('global.view') }}
                                </a>

                                <a class="btn btn-xs btn-info" href="{{ route('admin.users.edit', $user->id) }}">
                                    {{ trans('global.edit') }}
                                </a>

                                <form action="{{ route('admin.users.destroy', $user->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                    <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                </form>

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>


    </div>
</div>
@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('users_manage')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.users.mass_destroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-User:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})

</script>
@endsection

resources/views/admin/fpo/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.user.title') }}
    </div>

    <div class="card-body">
        <div class="mb-2">
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.user.fields.id') }}
                        </th>
                        <td>
                            {{ $user->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.user.fields.name') }}
                        </th>
                        <td>
                            {{ $user->name }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.user.fields.email') }}
                        </th>
                        <td>
                            {{ $user->email }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Roles
                        </th>
                        <td>
                            @foreach($user->roles()->pluck('name') as $role)
                                <span class="label label-info label-many">{{ $role }}</span>
                            @endforeach
                        </td>
                    </tr>
                </tbody>
            </table>
            <a style="margin-top:20px;" class="btn btn-default" href="{{ url()->previous() }}">
                {{ trans('global.back_to_list') }}
            </a>
        </div>


    </div>
</div>
@endsection